# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: streaming.proto for package 'streaming'

require 'grpc'
require 'streaming_pb'

module Streaming
  module Repository
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'streaming.Repository'

      # client-side streaming RPC
      rpc :store, stream(Item), StoreReply
      # server-side streaming RPC
      rpc :fetch, FetchRequest, stream(Item)
      # bidirectional streaming RPC
      rpc :storeAndFetch, stream(Item), stream(Item)
    end

    Stub = Service.rpc_stub_class
  end
end
