# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "streaming.Item" do
    optional :uuid, :string, 1
    optional :name, :string, 2
  end
  add_message "streaming.StoreReply" do
    optional :message, :string, 1
  end
  add_message "streaming.FetchRequest" do
    optional :num_items, :int32, 1
  end
end

module Streaming
  Item = Google::Protobuf::DescriptorPool.generated_pool.lookup("streaming.Item").msgclass
  StoreReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("streaming.StoreReply").msgclass
  FetchRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("streaming.FetchRequest").msgclass
end
